version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: bcpc_user
      POSTGRES_PASSWORD: bcpc_password
      POSTGRES_DB: bcpc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bcpc-app:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./outputs:/app/outputs
    environment:
      - PYTHONPATH=/app
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  postgres_data:
