version: "3.8"

services:
  bcpc:
    build:
      context: .
    container_name: bcpc
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./:/workspace
    ports:
      - "8888:8888"   # Jupyter notebooks
    command: >
      bash -c "jupyter notebook --ip=0.0.0.0 --no-browser
               --NotebookApp.token='' --NotebookApp.password=''"
