version: '3.8'

services:
  # Development service for pipeline
  pipeline-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: railway-pipeline:dev
    container_name: railway-pipeline-dev
    volumes:
      # Mount entire project
      - .:/workspace
      # Mount Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Persistent cache
      - railway-cache:/home/railway/.cache
      # Persistent venv (optional, for faster rebuilds)
      - railway-venv:/workspace/.venv
    environment:
      - PYTHONPATH=/workspace:${PYTHONPATH}
      - OPENTOPO_API_KEY=${OPENTOPO_API_KEY}
      - PIPELINE_MODE=development
    ports:
      - "8888:8888"  # Jupyter
      - "8000:8000"  # Web server
    stdin_open: true
    tty: true
    command: /bin/bash

  # Production service for pipeline
  pipeline-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: railway-pipeline:prod
    container_name: railway-pipeline-prod
    volumes:
      - ./input:/workspace/input:ro
      - ./output:/workspace/output
      - ./data:/workspace/data
    environment:
      - OPENTOPO_API_KEY=${OPENTOPO_API_KEY}
      - PIPELINE_MODE=production
    command: ["pipeline.cli", "--help"]

  # Jupyter notebook service
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: railway-pipeline:dev
    container_name: railway-jupyter
    volumes:
      - .:/workspace
      - railway-cache:/home/railway/.cache
    environment:
      - PYTHONPATH=/workspace:${PYTHONPATH}
    ports:
      - "8888:8888"
    command: poetry run jupyter notebook --ip=0.0.0.0 --no-browser --allow-root

volumes:
  railway-cache:
  railway-venv: