services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: rail-scheduler-app
    volumes:
      - ./:/workspace
      - dagster_home:/workspace/.dagster
    environment:
      DAGSTER_HOME: /workspace/.dagster
    ports:
      - "3000:3000"      # Dagster Web UI
    command: >
      bash -c "
        # 1) one-shot materialisation (will overwrite JSON / outputs)
        dagster asset materialize -m pipeline &&
        # 2) then keep Dagster Web UI running
        dagster webserver -h 0.0.0.0 -p 3000 -m pipeline
      "
