name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rail-scheduler:latest   # same image as devcontainer
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          python -m pytest
      - name: Run headless pipeline
        run: |
          dagster asset materialize -m pipeline.assets
